### ISSUE TITLE
test_integrated_query.py::test_two_simultaneous_runs fails

### ISSUE THREAD

**Issue by sudo-panda** [iris-hep/func_adl_xAOD#132]
Error occurs during docker execution:

```
/workdir/rel/source/analysis/Root/query.cxx: In member function 'virtual StatusCode query::execute()':
/workdir/rel/source/analysis/Root/query.cxx:100:19: warning: unused variable 'i_obj12' [-Wunused-variable]
         for (auto i_obj12 : *tracks10)
                   ^~~~~~~
/workdir/rel/source/analysis/Root/query.cxx:76:15: warning: unused variable 'i_obj9' [-Wunused-variable]
     for (auto i_obj9 : *jets8)
               ^~~~~~
Traceback (most recent call last):
  File "../source/analysis/share/ATestRun_eljob.py", line 58, in <module>
    driver.submit(job, options.submission_dir)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  void EL::Driver::submit(const EL::Job& job, const string& location) =>
    failed to submit job (C++ exception of type runtime_error)
  void EL::Driver::submit(const EL::Job& job, const string& location, string& actualLocation) =>
    takes at least 3 arguments (2 given)
```

**Comment by gordonwatts** [comment]
Oh - that is weird - why would there be two `EL::Driver::sibumit`'s? Is this on the atlas side?

**Comment by sudo-panda** [comment]
Yeah it is on the atlas side

**Comment by gordonwatts** [comment]
Running this in the ide to look at errors, I see some weird stuff. For example:

```
ERROR    tests.atlas.xaod.LocalFile:LocalFile.py:103   Package.EventLoop        INFO    Processing events 0-10 in file file:///data/jets_10_events.root
ERROR    tests.atlas.xaod.LocalFile:LocalFile.py:103   xAOD::TEvent::connectB... WARNING No metadata available for branch: AntiKt4EMTopJets
ERROR    tests.atlas.xaod.LocalFile:LocalFile.py:103   xAOD::TEvent::connectB... WARNING Branch "AntiKt4EMTopJets" not available on input
ERROR    tests.atlas.xaod.LocalFile:LocalFile.py:103   xAOD::TEvent::retrieve    WARNING Couldn't (const) retrieve "DataVector<xAOD::Jet_v1>/AntiKt4EMTopJets"
ERROR    tests.atlas.xaod.LocalFile:LocalFile.py:103   AnalysisAlg              ERROR   /workdir/rel/source/analysis/Root/query.cxx:70 (virtual StatusCode query::execute()): Failed to call "evtStore()->retrieve(result, "AntiKt4EMTopJets")"
```

The metadata warning is something I might expect if the xAODJet link was missing - thought that would be a DICT error, and I've verified that is indeed linked in.

**Comment by gordonwatts** [comment]
Hey - I learned how to use git bisect! :-) This is the (first check-in that is [bad](https://github.com/iris-hep/func_adl_xAOD/commit/0f2ee134373c94eec0618bab827c352173f84320)

**Comment by sudo-panda** [comment]
The commit that you mentioned might be a false positive as at that point in time I wasn't committing after running each tests. I was committing to save the chunk of work done and then in the later commits fixing the tests. 

Another thing is that I have run all tests before we merged #121 and all of them were working, not together but at least individually. But now if we checkout to it the tests fail.

Could the docker image be at fault here. Like some update in Atlas software that might have caused this?

**Comment by gordonwatts** [comment]
If the docker image were bad, then the older tests wouldn't work either. Also, the docker image is tagged, so it can't change (unless docker is broken).

**Comment by sudo-panda** [comment]
We are using `atlas/analysis_base:latest` as the docker image. So it will change if they add newer versions. It has had a push 9 days ago as seen [here](https://hub.docker.com/r/atlas/analysisbase/tags?page=1&ordering=last_updated). Maybe that broke the pipeline?

I will try changing the version and running the test.

**Comment by gordonwatts** [comment]
Problem was a mispelled topo jets container name: https://github.com/iris-hep/func_adl_xAOD/compare/gordonwatts/issue132
