### ISSUE TITLE
Implement all the variables for the CMS Run 1 AOD Demo

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/func_adl_xAOD#143]
The [run 1 demo](https://github.com/cms-opendata-analyses/HiggsExample20112012) from CMS makes a final Higgs to 4 lepton plot. Looking through that there are a number of variables that are extracted to make the plot and selections that require some more complex type information than is currently supported by the cms run 1 aod extractor.

This issue is to complete the set of variables required for extraction.

**Comment by sudo-panda** [comment]
List of variables that need to be supported: 

- [ ] HitPattern 
- [ ] GsfElectron

**Comment by gordonwatts** [comment]
Meeting minutes from [a detailed](https://hackmd.io/Ep7AWxW4QDew4suO4tm44A?both) discussion of this...

# How to do SelectIndex

## Experiment's Datamodel

```
class Event:
    @property
    def tracks(self) -> Array[Track]

class Track:
    @property
    def pt(self) -> float
    
    @property
    def hitPattern(self) -> HitPattern
    
class HitPattern:
    @property
    def nHits(self) -> int
    
    def getHitPattern(self, i: int) -> int
    
    def validHitFilter(self, hp: int) -> bool
```

## `func_adl` Query

Want the track pt's of all tracks with more than 5 valid hits (in the hit pattern mask)

Define `events` as our source dataset upon which all `func_adl` queries run (e.g. `ObjectStream`)

Low level `func_adl`:
```
events
    .SelectMany(e: e.tracks())
    .Where(t: Range(0, t.hitPattern().nHits)
                 .Select(nth: t.hitPattern().getHitPattern(nth)))
                 .Where(hp: t.hitPattern.validHitFilter(hp))
                 .Count() > 5
           )
    .Select(t: t.pt())
```

Comments:
- Do we need support for literals (like zero)?
    - Things like `array[0]` are supported already, so it should be
    - See [`visit_Num`](https://github.com/iris-hep/func_adl_xAOD/blob/master/func_adl_xAOD/common/ast_to_cpp_translator.py#L797)
- `Range` specification - `def Range(start_index: int, length: int) -> Array[int]`
    - Patterned off the LINQ [`Range`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?view=net-5.0)
    - Note that `Range` is a standalone function and source of a stream of objects (which happen to be numbers).
    - In `func_adl` how is `Range` defined?
        - `def Range(start_index: int, length: int) -> ObjectStream[int]`
        - Will have to do `from func_adl import Range` before you can use this.
        - This is common code for ATLAS and CMS...
        - Implement in C++ as `for(index = start_index; index < length; index++) {...}`???

## Using `SelectIndex`

```
events
    .SelectMany(e: e.tracks())
    .Where(t: SelectIndex(t.hitPattern().nHits, nth: t.hitPattern().getHitPattern(nth))
                 .Where(hp: t.hitPattern.validHitFilter(hp))
                 .Count() > 5
           )
    .Select(t: t.pt())
```

Comments
- `SelectIndex` isn't a good name for this

If we added `SelectIndex`:

- Have it as syntatic sugar
- Translated into `Range` and `Select` by the short cuts file (similar to [aggregate](https://github.com/iris-hep/func_adl/blob/09b755dd85dae9d399756cb089e1cffcbaedf018/func_adl/ast/aggregate_shortcuts.py)).

#### LINQ Query:
```
events
    .SelectMany(e: e.tracks("Tracks"))
    .Where(t: Range(0, t.hitPattern().nHits)
                 .Select(nth: t.hitPattern().getHitPattern(nth)))
                 .Where(hp: t.hitPattern().validHitFilter(hp))
                 .Count() > 5
           )
    .Select(t: t.pt())
```

#### C++ Code

```
Tracks = iEvent.getByLabel("Tracks")

for(auto *t : Tracks) {
    int c =0 ;
    int length = t.hitPattern().nHits();
    int start_index = 0;
    for(int i=start_index; i<length; i++) {
        hp = t.hitPattern().getHitPattern(i);
        if(t.hitPattern().validHitFilter(hp)) {
          c++;
        }
    }
    
    if(c>5) {
        double p = t.pt();
        ttree->Fill(p);
    }
}

**Comment by gordonwatts** [comment]
This was done!
